hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - process: process1
  - model: model1
  - _self_

data:
  raw: data/raw/Fish.csv
  processed: data/processed/processed.csv
  final: data/final/target.csv